#pragma once

/**
 * Name: Borderlands_3
 * Version: 4.20.3
 */

#include "../SDK.h"

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
	// --------------------------------------------------
	// # Structs
	// --------------------------------------------------
	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_ED389ABB48D67538B37F59B18C24DDF2
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_ED389ABB48D67538B37F59B18C24DDF2_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_9252354142ED505FD2E3B8A613700F18
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_9252354142ED505FD2E3B8A613700F18_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_A2C4F1EC4CDE9890986FAB88DFD6BBBE
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_A2C4F1EC4CDE9890986FAB88DFD6BBBE_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_E240F95A401072EF32B27EB594EDF607
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_E240F95A401072EF32B27EB594EDF607_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_BlendSpacePlayer_E8136BFD4735DCC4511EC3AA79923321
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_BlendSpacePlayer_E8136BFD4735DCC4511EC3AA79923321_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_ApplyAdditive_07C45E674EAA2FF3E9E8DCBCF41920F5
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_ApplyAdditive_07C45E674EAA2FF3E9E8DCBCF41920F5_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_77EB1FA74CB963269BE491B3FED55207
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_77EB1FA74CB963269BE491B3FED55207_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_396E43C34AB85BA94ACCFF9BAD2EB96E
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_396E43C34AB85BA94ACCFF9BAD2EB96E_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_09569D5C4EBCD1DEF5E900BFF9477A53
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_09569D5C4EBCD1DEF5E900BFF9477A53_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_106F22CF43ECFB85DFFDFDB059F96597
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_106F22CF43ECFB85DFFDFDB059F96597_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_RotationOffsetBlendSpace_A0057AB14870D1D2ADB9F48664881373
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_RotationOffsetBlendSpace_A0057AB14870D1D2ADB9F48664881373_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_BlendListByBool_6594A2B941E2E241E62AACA3A42A3311
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_BlendListByBool_6594A2B941E2E241E62AACA3A42A3311_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_RotationOffsetBlendSpace_463F93DB4B9B715F0FF6089349EE97BE
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_RotationOffsetBlendSpace_463F93DB4B9B715F0FF6089349EE97BE_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_BlendListByBool_705EFBA3465EA2632068B697B888025C
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_BlendListByBool_705EFBA3465EA2632068B697B888025C_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_DC0DBA164D002CB8049F13A2CF513B8A
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_DC0DBA164D002CB8049F13A2CF513B8A_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_2AFEA2FE4221E5CAE420E3A1240E8D76
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_2AFEA2FE4221E5CAE420E3A1240E8D76_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_3ED701F140785DBD69E8939FE1DFB7FA
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_AnimGraphNode_TransitionResult_3ED701F140785DBD69E8939FE1DFB7FA_Params
	{	};

	/**
	 * Function BPAnim_SirenBrawler_GhostArms_3rd.BPAnim_SirenBrawler_GhostArms_3rd_C.ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd
	 */
	struct UBPAnim_SirenBrawler_GhostArms_3rd_C_ExecuteUbergraph_BPAnim_SirenBrawler_GhostArms_3rd_Params
	{
	public:
		int32_t                                                    EntryPoint;                                              // 0x0000(0x0004)  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
