#pragma once

/**
 * Name: DarkAndDarker-Playtest
 * Version: Playtest_3_Hotfix_3
 */

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
	// --------------------------------------------------
	// # Classes
	// --------------------------------------------------
	/**
	 * AnimBlueprintGeneratedClass ABP_PlayerCharacter.ABP_PlayerCharacter_C
	 * Size -> 0x62EA (FullSize[0x680A] - InheritedSize[0x0520])
	 */
	class UABP_PlayerCharacter_C : public UDCPlayerCharacterAnimInstanceBase
	{
	public:
		struct FPointerToUberGraphFrame                            UberGraphFrame;                                          // 0x0520(0x0008) ZeroConstructor, Transient, DuplicateTransient
		struct UABP_PlayerCharacter_C_FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                                 // 0x0528(0x0110) HasGetValueTypeHash
		struct FAnimSubsystemInstance                              AnimBlueprintExtension_PropertyAccess;                   // 0x0638(0x0008)
		struct FAnimSubsystemInstance                              AnimBlueprintExtension_Base;                             // 0x0640(0x0008)
		struct FAnimNode_Root                                      AnimGraphNode_Root;                                      // 0x0648(0x0020)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_36;                       // 0x0668(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_35;                       // 0x0690(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_34;                       // 0x06B8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_33;                       // 0x06E0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_32;                       // 0x0708(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_48;                          // 0x0730(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_28;                         // 0x0758(0x0040)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_15;                       // 0x0798(0x00E0)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_27;                         // 0x0878(0x0040)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_9;                           // 0x08B8(0x00C8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_43;                            // 0x0980(0x0020)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_31;                       // 0x09A0(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_26;                         // 0x09C8(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_42;                            // 0x0A08(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_47;                          // 0x0A28(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_25;                         // 0x0A50(0x0040)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_8;                           // 0x0A90(0x00C8)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_14;                       // 0x0B58(0x00E0)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_24;                         // 0x0C38(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_41;                            // 0x0C78(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_46;                          // 0x0C98(0x0028)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_13;                       // 0x0CC0(0x00E0)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_23;                         // 0x0DA0(0x0040)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_7;                           // 0x0DE0(0x00C8)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_22;                         // 0x0EA8(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_40;                            // 0x0EE8(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_17;                           // 0x0F08(0x00B8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_39;                            // 0x0FC0(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_45;                          // 0x0FE0(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_38;                            // 0x1008(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_16;                           // 0x1028(0x00B8)
		struct FAnimNode_Slot                                      AnimGraphNode_Slot;                                      // 0x10E0(0x0048)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_18;                         // 0x1128(0x0108)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_44;                          // 0x1230(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_30;                       // 0x1258(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_29;                       // 0x1280(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_21;                         // 0x12A8(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_37;                            // 0x12E8(0x0020)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_20;                         // 0x1308(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_36;                            // 0x1348(0x0020)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_12;                       // 0x1368(0x0068)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_12;                       // 0x13D0(0x00E0)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_20;                        // 0x14B0(0x0048)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_11;                       // 0x14F8(0x0068)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_10;                       // 0x1560(0x0068)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_35;                            // 0x15C8(0x0020)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_19;                         // 0x15E8(0x0040)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_11;                       // 0x1628(0x00E0)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_19;                        // 0x1708(0x0048)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_18;                         // 0x1750(0x0040)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_17;                         // 0x1790(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_34;                            // 0x17D0(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_15;                           // 0x17F0(0x00B8)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_17;                         // 0x18A8(0x0108)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_28;                       // 0x19B0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_27;                       // 0x19D8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_26;                       // 0x1A00(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_25;                       // 0x1A28(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_16;                         // 0x1A50(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_33;                            // 0x1A90(0x0020)
		struct FAnimNode_RandomPlayer                              AnimGraphNode_RandomPlayer;                              // 0x1AB0(0x0078)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_32;                            // 0x1B28(0x0020)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_15;                         // 0x1B48(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_31;                            // 0x1B88(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_14;                           // 0x1BA8(0x00B8)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_10;                       // 0x1C60(0x00E0)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_16;                         // 0x1D40(0x0108)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_43;                          // 0x1E48(0x0028)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_18;                        // 0x1E70(0x0048)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_42;                          // 0x1EB8(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_41;                          // 0x1EE0(0x0028)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_9;                        // 0x1F08(0x00E0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_40;                          // 0x1FE8(0x0028)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_17;                        // 0x2010(0x0048)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_16;                        // 0x2058(0x0048)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_15;                        // 0x20A0(0x0048)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_39;                          // 0x20E8(0x0028)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_8;                        // 0x2110(0x00E0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_38;                          // 0x21F0(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_37;                          // 0x2218(0x0028)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_14;                        // 0x2240(0x0048)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_36;                          // 0x2288(0x0028)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_7;                        // 0x22B0(0x00E0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_35;                          // 0x2390(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_30;                            // 0x23B8(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_13;                           // 0x23D8(0x00B8)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_6;                        // 0x2490(0x00E0)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_34;                          // 0x2570(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_33;                          // 0x2598(0x0028)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_13;                        // 0x25C0(0x0048)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_15;                         // 0x2608(0x0108)
		struct FAnimNode_ConvertLocalToComponentSpace              AnimGraphNode_LocalToComponentSpace_2;                   // 0x2710(0x0020)
		struct FAnimNode_LegIK                                     AnimGraphNode_LegIK_2;                                   // 0x2730(0x00F8)
		struct FAnimNode_ConvertComponentToLocalSpace              AnimGraphNode_ComponentToLocalSpace_2;                   // 0x2828(0x0020)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_14;                         // 0x2848(0x0108)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_13;                         // 0x2950(0x0108)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_32;                          // 0x2A58(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_31;                          // 0x2A80(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_30;                          // 0x2AA8(0x0028)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_12;                        // 0x2AD0(0x0048)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_29;                          // 0x2B18(0x0028)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_5;                        // 0x2B40(0x00E0)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_29;                            // 0x2C20(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_12;                           // 0x2C40(0x00B8)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_4;                        // 0x2CF8(0x00E0)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_14;                         // 0x2DD8(0x0040)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_28;                          // 0x2E18(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_27;                          // 0x2E40(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_26;                          // 0x2E68(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_25;                          // 0x2E90(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_13;                         // 0x2EB8(0x0040)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_6;                           // 0x2EF8(0x00C8)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_11;                        // 0x2FC0(0x0048)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_10;                        // 0x3008(0x0048)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_3;                        // 0x3050(0x00E0)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_5;                           // 0x3130(0x00C8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_28;                            // 0x31F8(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_11;                           // 0x3218(0x00B8)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_24;                       // 0x32D0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_23;                       // 0x32F8(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_12;                         // 0x3320(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_27;                            // 0x3360(0x0020)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_11;                         // 0x3380(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_26;                            // 0x33C0(0x0020)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_9;                        // 0x33E0(0x0068)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_25;                            // 0x3448(0x0020)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_10;                         // 0x3468(0x0040)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend_2;                        // 0x34A8(0x00E0)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_9;                         // 0x3588(0x0048)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_9;                          // 0x35D0(0x0040)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_8;                          // 0x3610(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_24;                            // 0x3650(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_10;                           // 0x3670(0x00B8)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_12;                         // 0x3728(0x0108)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_24;                          // 0x3830(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_23;                          // 0x3858(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_22;                          // 0x3880(0x0028)
		struct FAnimNode_RotationOffsetBlendSpace                  AnimGraphNode_RotationOffsetBlendSpace_6;                // 0x38A8(0x0110)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_8;                         // 0x39B8(0x0048)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_7;                         // 0x3A00(0x0048)
		struct FAnimNode_RotationOffsetBlendSpace                  AnimGraphNode_RotationOffsetBlendSpace_5;                // 0x3A48(0x0110)
		struct FAnimNode_RotationOffsetBlendSpace                  AnimGraphNode_RotationOffsetBlendSpace_4;                // 0x3B58(0x0110)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_23;                            // 0x3C68(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_9;                            // 0x3C88(0x00B8)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_21;                          // 0x3D40(0x0028)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_11;                         // 0x3D68(0x0108)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_10;                         // 0x3E70(0x0108)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_9;                          // 0x3F78(0x0108)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_22;                       // 0x4080(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_21;                       // 0x40A8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_20;                       // 0x40D0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_19;                       // 0x40F8(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_7;                          // 0x4120(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_22;                            // 0x4160(0x0020)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_18;                       // 0x4180(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_17;                       // 0x41A8(0x0028)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_8;                        // 0x41D0(0x0068)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_21;                            // 0x4238(0x0020)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_6;                          // 0x4258(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_20;                            // 0x4298(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_8;                            // 0x42B8(0x00B8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_19;                            // 0x4370(0x0020)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_5;                          // 0x4390(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_18;                            // 0x43D0(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_20;                          // 0x43F0(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_17;                            // 0x4418(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_7;                            // 0x4438(0x00B8)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_8;                          // 0x44F0(0x0108)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_19;                          // 0x45F8(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_18;                          // 0x4620(0x0028)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_7;                          // 0x4648(0x0108)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_6;                         // 0x4750(0x0048)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_17;                          // 0x4798(0x0028)
		struct FAnimNode_LayeredBoneBlend                          AnimGraphNode_LayeredBoneBlend;                          // 0x47C0(0x00E0)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_16;                       // 0x48A0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_15;                       // 0x48C8(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_16;                          // 0x48F0(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_16;                            // 0x4918(0x0020)
		struct FAnimNode_ConvertComponentToLocalSpace              AnimGraphNode_ComponentToLocalSpace;                     // 0x4938(0x0020)
		struct FAnimNode_HandIKRetargeting                         AnimGraphNode_HandIKRetargeting;                         // 0x4958(0x0120)
		struct FAnimNode_LegIK                                     AnimGraphNode_LegIK;                                     // 0x4A78(0x00F8)
		struct FAnimNode_ConvertLocalToComponentSpace              AnimGraphNode_LocalToComponentSpace;                     // 0x4B70(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_15;                          // 0x4B90(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_15;                            // 0x4BB8(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_6;                            // 0x4BD8(0x00B8)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_14;                       // 0x4C90(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_13;                       // 0x4CB8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_12;                       // 0x4CE0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_11;                       // 0x4D08(0x0028)
		struct FAnimNode_RotationOffsetBlendSpace                  AnimGraphNode_RotationOffsetBlendSpace_3;                // 0x4D30(0x0110)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_14;                          // 0x4E40(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_14;                            // 0x4E68(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_13;                          // 0x4E88(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_13;                            // 0x4EB0(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_12;                          // 0x4ED0(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_12;                            // 0x4EF8(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_5;                            // 0x4F18(0x00B8)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_6;                          // 0x4FD0(0x0108)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_11;                          // 0x50D8(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_10;                          // 0x5100(0x0028)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_5;                          // 0x5128(0x0108)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_10;                       // 0x5230(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_9;                        // 0x5258(0x0028)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_4;                          // 0x5280(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_11;                            // 0x52C0(0x0020)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_3;                          // 0x52E0(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_10;                            // 0x5320(0x0020)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer_2;                          // 0x5340(0x0040)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_9;                             // 0x5380(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_9;                           // 0x53A0(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_8;                             // 0x53C8(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_4;                            // 0x53E8(0x00B8)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_4;                          // 0x54A0(0x0108)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_8;                        // 0x55A8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_7;                        // 0x55D0(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_6;                        // 0x55F8(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_5;                        // 0x5620(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_4;                        // 0x5648(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_3;                        // 0x5670(0x0028)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult_2;                        // 0x5698(0x0028)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_7;                        // 0x56C0(0x0068)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_5;                         // 0x5728(0x0048)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_4;                         // 0x5770(0x0048)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_6;                        // 0x57B8(0x0068)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_4;                           // 0x5820(0x00C8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_5;                        // 0x58E8(0x0068)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_8;                           // 0x5950(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_7;                             // 0x5978(0x0020)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_4;                        // 0x5998(0x0068)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_3;                         // 0x5A00(0x0048)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool_2;                         // 0x5A48(0x0048)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_3;                        // 0x5A90(0x0068)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_3;                           // 0x5AF8(0x00C8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer_2;                        // 0x5BC0(0x0068)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_7;                           // 0x5C28(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_6;                             // 0x5C50(0x0020)
		struct FAnimNode_TransitionResult                          AnimGraphNode_TransitionResult;                          // 0x5C70(0x0028)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive_2;                           // 0x5C98(0x00C8)
		struct FAnimNode_BlendSpacePlayer                          AnimGraphNode_BlendSpacePlayer;                          // 0x5D60(0x0068)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_6;                           // 0x5DC8(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_5;                             // 0x5DF0(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_5;                           // 0x5E10(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_4;                             // 0x5E38(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_3;                            // 0x5E58(0x00B8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_3;                             // 0x5F10(0x0020)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_4;                           // 0x5F30(0x0028)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult_2;                             // 0x5F58(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine_2;                            // 0x5F78(0x00B8)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_3;                          // 0x6030(0x0108)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose_2;                          // 0x6138(0x0108)
		struct FAnimNode_RotationOffsetBlendSpace                  AnimGraphNode_RotationOffsetBlendSpace_2;                // 0x6240(0x0110)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_3;                           // 0x6350(0x0028)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose_2;                           // 0x6378(0x0028)
		struct FAnimNode_BlendListByBool                           AnimGraphNode_BlendListByBool;                           // 0x63A0(0x0048)
		struct FAnimNode_SequencePlayer                            AnimGraphNode_SequencePlayer;                            // 0x63E8(0x0040)
		struct FAnimNode_ApplyAdditive                             AnimGraphNode_ApplyAdditive;                             // 0x6428(0x00C8)
		struct FAnimNode_StateResult                               AnimGraphNode_StateResult;                               // 0x64F0(0x0020)
		struct FAnimNode_StateMachine                              AnimGraphNode_StateMachine;                              // 0x6510(0x00B8)
		struct FAnimNode_RotationOffsetBlendSpace                  AnimGraphNode_RotationOffsetBlendSpace;                  // 0x65C8(0x0110)
		struct FAnimNode_SaveCachedPose                            AnimGraphNode_SaveCachedPose;                            // 0x66D8(0x0108)
		struct FAnimNode_UseCachedPose                             AnimGraphNode_UseCachedPose;                             // 0x67E0(0x0028)
		bool                                                       isCrawling;                                              // 0x6808(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
		bool                                                       isBlocking;                                              // 0x6809(0x0001) Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash

	public:
		void AnimGraph(struct FPoseLink* AnimGraph);
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_9DDEB3C44D531DBB84C2CAAB5113B160();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_DA79062E42573F99E8AEE6B24488F50A();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_BlendListByBool_30F59DF148707D4D1F2444A7967C2F2E();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_BlendListByBool_083F6A484A9BCD020EA31A9D5197BC0A();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_118EA37E42CA4A18089809B9A605E2B2();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_367F10D4475CB668EA1631A747178E80();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_5F984BBF44E874B2884C949EFA77C710();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_F2E0D5A64F3D20384B042CB49DD8AC7F();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_1507091E4B2B2A113FBA9D9F17177441();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_96E216264CADA449228B2792F8E1977B();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_1556C0264A85E13C9ABA4DAB5061CD49();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_CAB697824B803EDCCD1EE1A637668658();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_BB0AB53946BB6E087646D3AE770B816C();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_BlendListByBool_D0FECE0847E8862D2BE5569779D07C74();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_BlendListByBool_23FBFAB141026CF3A0E1BE8D7520C71A();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_BlendListByBool_71B4C5784FA96616F1D53B869CBB93CA();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_BlendListByBool_FC5F51FC447C8638EBCEEFAC3D32BD3E();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_15E2D06549259FA91E6965A6046A9299();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_8E18B53F404516307185238E4C01BBDE();
		void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_PlayerCharacter_AnimGraphNode_TransitionResult_AF28AD104120D91B721710A6BEBBCD34();
		void ExecuteUbergraph_ABP_PlayerCharacter(int32_t EntryPoint);
		static UClass* StaticClass();
	};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
