#pragma once

/**
 * Name: DarkAndDarker-Playtest
 * Version: Playtest_3_Hotfix_3
 */

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
	// --------------------------------------------------
	// # Enums
	// --------------------------------------------------
	/**
	 * BoneSkeletalMesh SK_PC_Man_Head.SK_PC_Man_Head
	 */
	enum class EBone_SK_PC_Man_Head : uint8_t
	{
		Root                = 0,
		pelvis              = 1,
		spine_01            = 2,
		spine_02            = 3,
		spine_03            = 4,
		clavicle_l          = 5,
		upperarm_l          = 6,
		lowerarm_l          = 7,
		hand_l              = 8,
		thumb_01_l          = 9,
		thumb_02_l          = 10,
		thumb_03_l          = 11,
		index_01_l          = 12,
		index_02_l          = 13,
		index_03_l          = 14,
		middle_01_l         = 15,
		middle_02_l         = 16,
		middle_03_l         = 17,
		ring_01_l           = 18,
		ring_02_l           = 19,
		ring_03_l           = 20,
		pinky_01_l          = 21,
		pinky_02_l          = 22,
		pinky_03_l          = 23,
		shield_l            = 24,
		lowerarm_twist_01_l = 25,
		upperarm_twist_01_l = 26,
		neck_01             = 27,
		Head                = 28,
		clavicle_r          = 29,
		upperarm_r          = 30,
		lowerarm_r          = 31,
		lowerarm_twist_01_r = 32,
		shield_r            = 33,
		hand_r              = 34,
		pinky_01_r          = 35,
		pinky_02_r          = 36,
		pinky_03_r          = 37,
		ring_01_r           = 38,
		ring_02_r           = 39,
		ring_03_r           = 40,
		middle_01_r         = 41,
		middle_02_r         = 42,
		middle_03_r         = 43,
		index_01_r          = 44,
		index_02_r          = 45,
		index_03_r          = 46,
		thumb_01_r          = 47,
		thumb_02_r          = 48,
		thumb_03_r          = 49,
		upperarm_twist_01_r = 50,
		thigh_l             = 51,
		calf_l              = 52,
		foot_l              = 53,
		ball_l              = 54,
		thigh_r             = 55,
		calf_r              = 56,
		foot_r              = 57,
		ball_r              = 58,
		ik_foot_root        = 59,
		ik_foot_l           = 60,
		ik_foot_r           = 61,
		ik_hand_root        = 62,
		ik_hand_gun         = 63,
		ik_hand_l           = 64,
		weapon_l            = 65,
		ik_hand_r           = 66,
		weapon_r            = 67,
		camera_root         = 68,
		camera_rot_root     = 69,
		Camera              = 70,
		calf_twist_01_l     = 71,
		thigh_twist_01_l    = 72,
		calf_twist_01_r     = 73,
		thigh_twist_01_r    = 74,
		eyelid_l            = 75,
		eyelid_r            = 76
	};

	/**
	 * BoneSkeletalMesh SK_Gjermundbu.SK_Gjermundbu
	 */
	enum class EBone_SK_Gjermundbu : uint8_t
	{
		Root                = 0,
		pelvis              = 1,
		spine_01            = 2,
		spine_02            = 3,
		spine_03            = 4,
		clavicle_l          = 5,
		upperarm_l          = 6,
		lowerarm_l          = 7,
		hand_l              = 8,
		thumb_01_l          = 9,
		thumb_02_l          = 10,
		thumb_03_l          = 11,
		index_01_l          = 12,
		index_02_l          = 13,
		index_03_l          = 14,
		middle_01_l         = 15,
		middle_02_l         = 16,
		middle_03_l         = 17,
		ring_01_l           = 18,
		ring_02_l           = 19,
		ring_03_l           = 20,
		pinky_01_l          = 21,
		pinky_02_l          = 22,
		pinky_03_l          = 23,
		shield_l            = 24,
		lowerarm_twist_01_l = 25,
		upperarm_twist_01_l = 26,
		neck_01             = 27,
		Head                = 28,
		clavicle_r          = 29,
		upperarm_r          = 30,
		lowerarm_r          = 31,
		lowerarm_twist_01_r = 32,
		shield_r            = 33,
		hand_r              = 34,
		pinky_01_r          = 35,
		pinky_02_r          = 36,
		pinky_03_r          = 37,
		ring_01_r           = 38,
		ring_02_r           = 39,
		ring_03_r           = 40,
		middle_01_r         = 41,
		middle_02_r         = 42,
		middle_03_r         = 43,
		index_01_r          = 44,
		index_02_r          = 45,
		index_03_r          = 46,
		thumb_01_r          = 47,
		thumb_02_r          = 48,
		thumb_03_r          = 49,
		upperarm_twist_01_r = 50,
		thigh_l             = 51,
		calf_l              = 52,
		foot_l              = 53,
		ball_l              = 54,
		thigh_r             = 55,
		calf_r              = 56,
		foot_r              = 57,
		ball_r              = 58,
		ik_foot_root        = 59,
		ik_foot_l           = 60,
		ik_foot_r           = 61,
		ik_hand_root        = 62,
		ik_hand_gun         = 63,
		ik_hand_l           = 64,
		weapon_l            = 65,
		ik_hand_r           = 66,
		weapon_r            = 67,
		camera_root         = 68,
		camera_rot_root     = 69,
		Camera              = 70,
		calf_twist_01_l     = 71,
		thigh_twist_01_l    = 72,
		calf_twist_01_r     = 73,
		thigh_twist_01_r    = 74,
		eyelid_l            = 75,
		eyelid_r            = 76
	};

	/**
	 * BoneSkeletalMesh SK_PC_Man_Gloves.SK_PC_Man_Gloves
	 */
	enum class EBone_SK_PC_Man_Gloves : uint8_t
	{
		Root                = 0,
		pelvis              = 1,
		spine_01            = 2,
		spine_02            = 3,
		spine_03            = 4,
		clavicle_l          = 5,
		upperarm_l          = 6,
		lowerarm_l          = 7,
		hand_l              = 8,
		thumb_01_l          = 9,
		thumb_02_l          = 10,
		thumb_03_l          = 11,
		index_01_l          = 12,
		index_02_l          = 13,
		index_03_l          = 14,
		middle_01_l         = 15,
		middle_02_l         = 16,
		middle_03_l         = 17,
		ring_01_l           = 18,
		ring_02_l           = 19,
		ring_03_l           = 20,
		pinky_01_l          = 21,
		pinky_02_l          = 22,
		pinky_03_l          = 23,
		shield_l            = 24,
		lowerarm_twist_01_l = 25,
		upperarm_twist_01_l = 26,
		neck_01             = 27,
		Head                = 28,
		clavicle_r          = 29,
		upperarm_r          = 30,
		lowerarm_r          = 31,
		lowerarm_twist_01_r = 32,
		shield_r            = 33,
		hand_r              = 34,
		pinky_01_r          = 35,
		pinky_02_r          = 36,
		pinky_03_r          = 37,
		ring_01_r           = 38,
		ring_02_r           = 39,
		ring_03_r           = 40,
		middle_01_r         = 41,
		middle_02_r         = 42,
		middle_03_r         = 43,
		index_01_r          = 44,
		index_02_r          = 45,
		index_03_r          = 46,
		thumb_01_r          = 47,
		thumb_02_r          = 48,
		thumb_03_r          = 49,
		upperarm_twist_01_r = 50,
		thigh_l             = 51,
		calf_l              = 52,
		foot_l              = 53,
		ball_l              = 54,
		thigh_r             = 55,
		calf_r              = 56,
		foot_r              = 57,
		ball_r              = 58,
		ik_foot_root        = 59,
		ik_foot_l           = 60,
		ik_foot_r           = 61,
		ik_hand_root        = 62,
		ik_hand_gun         = 63,
		ik_hand_l           = 64,
		weapon_l            = 65,
		ik_hand_r           = 66,
		weapon_r            = 67,
		camera_root         = 68,
		camera_rot_root     = 69,
		Camera              = 70,
		calf_twist_01_l     = 71,
		thigh_twist_01_l    = 72,
		calf_twist_01_r     = 73,
		thigh_twist_01_r    = 74,
		eyelid_l            = 75,
		eyelid_r            = 76
	};

	/**
	 * BoneSkeletalMesh SK_PC_Man_Chest.SK_PC_Man_Chest
	 */
	enum class EBone_SK_PC_Man_Chest : uint8_t
	{
		Root                = 0,
		pelvis              = 1,
		spine_01            = 2,
		spine_02            = 3,
		spine_03            = 4,
		clavicle_l          = 5,
		upperarm_l          = 6,
		lowerarm_l          = 7,
		hand_l              = 8,
		thumb_01_l          = 9,
		thumb_02_l          = 10,
		thumb_03_l          = 11,
		index_01_l          = 12,
		index_02_l          = 13,
		index_03_l          = 14,
		middle_01_l         = 15,
		middle_02_l         = 16,
		middle_03_l         = 17,
		ring_01_l           = 18,
		ring_02_l           = 19,
		ring_03_l           = 20,
		pinky_01_l          = 21,
		pinky_02_l          = 22,
		pinky_03_l          = 23,
		shield_l            = 24,
		lowerarm_twist_01_l = 25,
		upperarm_twist_01_l = 26,
		neck_01             = 27,
		Head                = 28,
		clavicle_r          = 29,
		upperarm_r          = 30,
		lowerarm_r          = 31,
		lowerarm_twist_01_r = 32,
		shield_r            = 33,
		hand_r              = 34,
		pinky_01_r          = 35,
		pinky_02_r          = 36,
		pinky_03_r          = 37,
		ring_01_r           = 38,
		ring_02_r           = 39,
		ring_03_r           = 40,
		middle_01_r         = 41,
		middle_02_r         = 42,
		middle_03_r         = 43,
		index_01_r          = 44,
		index_02_r          = 45,
		index_03_r          = 46,
		thumb_01_r          = 47,
		thumb_02_r          = 48,
		thumb_03_r          = 49,
		upperarm_twist_01_r = 50,
		thigh_l             = 51,
		calf_l              = 52,
		foot_l              = 53,
		ball_l              = 54,
		thigh_r             = 55,
		calf_r              = 56,
		foot_r              = 57,
		ball_r              = 58,
		ik_foot_root        = 59,
		ik_foot_l           = 60,
		ik_foot_r           = 61,
		ik_hand_root        = 62,
		ik_hand_gun         = 63,
		ik_hand_l           = 64,
		weapon_l            = 65,
		ik_hand_r           = 66,
		weapon_r            = 67,
		camera_root         = 68,
		camera_rot_root     = 69,
		Camera              = 70,
		calf_twist_01_l     = 71,
		thigh_twist_01_l    = 72,
		calf_twist_01_r     = 73,
		thigh_twist_01_r    = 74,
		eyelid_l            = 75,
		eyelid_r            = 76
	};

	/**
	 * BoneSkeletalMesh SK_PC_Man_Pants.SK_PC_Man_Pants
	 */
	enum class EBone_SK_PC_Man_Pants : uint8_t
	{
		Root                = 0,
		pelvis              = 1,
		spine_01            = 2,
		spine_02            = 3,
		spine_03            = 4,
		clavicle_l          = 5,
		upperarm_l          = 6,
		lowerarm_l          = 7,
		hand_l              = 8,
		thumb_01_l          = 9,
		thumb_02_l          = 10,
		thumb_03_l          = 11,
		index_01_l          = 12,
		index_02_l          = 13,
		index_03_l          = 14,
		middle_01_l         = 15,
		middle_02_l         = 16,
		middle_03_l         = 17,
		ring_01_l           = 18,
		ring_02_l           = 19,
		ring_03_l           = 20,
		pinky_01_l          = 21,
		pinky_02_l          = 22,
		pinky_03_l          = 23,
		shield_l            = 24,
		lowerarm_twist_01_l = 25,
		upperarm_twist_01_l = 26,
		neck_01             = 27,
		Head                = 28,
		clavicle_r          = 29,
		upperarm_r          = 30,
		lowerarm_r          = 31,
		lowerarm_twist_01_r = 32,
		shield_r            = 33,
		hand_r              = 34,
		pinky_01_r          = 35,
		pinky_02_r          = 36,
		pinky_03_r          = 37,
		ring_01_r           = 38,
		ring_02_r           = 39,
		ring_03_r           = 40,
		middle_01_r         = 41,
		middle_02_r         = 42,
		middle_03_r         = 43,
		index_01_r          = 44,
		index_02_r          = 45,
		index_03_r          = 46,
		thumb_01_r          = 47,
		thumb_02_r          = 48,
		thumb_03_r          = 49,
		upperarm_twist_01_r = 50,
		thigh_l             = 51,
		calf_l              = 52,
		foot_l              = 53,
		ball_l              = 54,
		thigh_r             = 55,
		calf_r              = 56,
		foot_r              = 57,
		ball_r              = 58,
		ik_foot_root        = 59,
		ik_foot_l           = 60,
		ik_foot_r           = 61,
		ik_hand_root        = 62,
		ik_hand_gun         = 63,
		ik_hand_l           = 64,
		weapon_l            = 65,
		ik_hand_r           = 66,
		weapon_r            = 67,
		camera_root         = 68,
		camera_rot_root     = 69,
		Camera              = 70,
		calf_twist_01_l     = 71,
		thigh_twist_01_l    = 72,
		calf_twist_01_r     = 73,
		thigh_twist_01_r    = 74,
		eyelid_l            = 75,
		eyelid_r            = 76
	};

	/**
	 * BoneSkeletalMesh SK_PC_Man_Boots.SK_PC_Man_Boots
	 */
	enum class EBone_SK_PC_Man_Boots : uint8_t
	{
		Root                = 0,
		pelvis              = 1,
		spine_01            = 2,
		spine_02            = 3,
		spine_03            = 4,
		clavicle_l          = 5,
		upperarm_l          = 6,
		lowerarm_l          = 7,
		hand_l              = 8,
		thumb_01_l          = 9,
		thumb_02_l          = 10,
		thumb_03_l          = 11,
		index_01_l          = 12,
		index_02_l          = 13,
		index_03_l          = 14,
		middle_01_l         = 15,
		middle_02_l         = 16,
		middle_03_l         = 17,
		ring_01_l           = 18,
		ring_02_l           = 19,
		ring_03_l           = 20,
		pinky_01_l          = 21,
		pinky_02_l          = 22,
		pinky_03_l          = 23,
		shield_l            = 24,
		lowerarm_twist_01_l = 25,
		upperarm_twist_01_l = 26,
		neck_01             = 27,
		Head                = 28,
		clavicle_r          = 29,
		upperarm_r          = 30,
		lowerarm_r          = 31,
		lowerarm_twist_01_r = 32,
		shield_r            = 33,
		hand_r              = 34,
		pinky_01_r          = 35,
		pinky_02_r          = 36,
		pinky_03_r          = 37,
		ring_01_r           = 38,
		ring_02_r           = 39,
		ring_03_r           = 40,
		middle_01_r         = 41,
		middle_02_r         = 42,
		middle_03_r         = 43,
		index_01_r          = 44,
		index_02_r          = 45,
		index_03_r          = 46,
		thumb_01_r          = 47,
		thumb_02_r          = 48,
		thumb_03_r          = 49,
		upperarm_twist_01_r = 50,
		thigh_l             = 51,
		calf_l              = 52,
		foot_l              = 53,
		ball_l              = 54,
		thigh_r             = 55,
		calf_r              = 56,
		foot_r              = 57,
		ball_r              = 58,
		ik_foot_root        = 59,
		ik_foot_l           = 60,
		ik_foot_r           = 61,
		ik_hand_root        = 62,
		ik_hand_gun         = 63,
		ik_hand_l           = 64,
		weapon_l            = 65,
		ik_hand_r           = 66,
		weapon_r            = 67,
		camera_root         = 68,
		camera_rot_root     = 69,
		Camera              = 70,
		calf_twist_01_l     = 71,
		thigh_twist_01_l    = 72,
		calf_twist_01_r     = 73,
		thigh_twist_01_r    = 74,
		eyelid_l            = 75,
		eyelid_r            = 76
	};

	/**
	 * BoneSkeletalMesh SK_ClothPants.SK_ClothPants
	 */
	enum class EBone_SK_ClothPants : uint8_t
	{
		Root                = 0,
		pelvis              = 1,
		spine_01            = 2,
		spine_02            = 3,
		spine_03            = 4,
		clavicle_l          = 5,
		upperarm_l          = 6,
		lowerarm_l          = 7,
		hand_l              = 8,
		thumb_01_l          = 9,
		thumb_02_l          = 10,
		thumb_03_l          = 11,
		index_01_l          = 12,
		index_02_l          = 13,
		index_03_l          = 14,
		middle_01_l         = 15,
		middle_02_l         = 16,
		middle_03_l         = 17,
		ring_01_l           = 18,
		ring_02_l           = 19,
		ring_03_l           = 20,
		pinky_01_l          = 21,
		pinky_02_l          = 22,
		pinky_03_l          = 23,
		shield_l            = 24,
		lowerarm_twist_01_l = 25,
		upperarm_twist_01_l = 26,
		neck_01             = 27,
		Head                = 28,
		clavicle_r          = 29,
		upperarm_r          = 30,
		lowerarm_r          = 31,
		lowerarm_twist_01_r = 32,
		shield_r            = 33,
		hand_r              = 34,
		pinky_01_r          = 35,
		pinky_02_r          = 36,
		pinky_03_r          = 37,
		ring_01_r           = 38,
		ring_02_r           = 39,
		ring_03_r           = 40,
		middle_01_r         = 41,
		middle_02_r         = 42,
		middle_03_r         = 43,
		index_01_r          = 44,
		index_02_r          = 45,
		index_03_r          = 46,
		thumb_01_r          = 47,
		thumb_02_r          = 48,
		thumb_03_r          = 49,
		upperarm_twist_01_r = 50,
		thigh_l             = 51,
		calf_l              = 52,
		foot_l              = 53,
		ball_l              = 54,
		thigh_r             = 55,
		calf_r              = 56,
		foot_r              = 57,
		ball_r              = 58,
		ik_foot_root        = 59,
		ik_foot_l           = 60,
		ik_foot_r           = 61,
		ik_hand_root        = 62,
		ik_hand_gun         = 63,
		ik_hand_l           = 64,
		weapon_l            = 65,
		ik_hand_r           = 66,
		weapon_r            = 67,
		camera_root         = 68,
		camera_rot_root     = 69,
		Camera              = 70,
		calf_twist_01_l     = 71,
		thigh_twist_01_l    = 72,
		calf_twist_01_r     = 73,
		thigh_twist_01_r    = 74,
		eyelid_l            = 75,
		eyelid_r            = 76
	};

	/**
	 * BoneSkeletalMesh SK_PC_Man.SK_PC_Man
	 */
	enum class EBone_SK_PC_Man : uint8_t
	{
		Root                = 0,
		pelvis              = 1,
		spine_01            = 2,
		spine_02            = 3,
		spine_03            = 4,
		clavicle_l          = 5,
		upperarm_l          = 6,
		lowerarm_l          = 7,
		hand_l              = 8,
		thumb_01_l          = 9,
		thumb_02_l          = 10,
		thumb_03_l          = 11,
		index_01_l          = 12,
		index_02_l          = 13,
		index_03_l          = 14,
		middle_01_l         = 15,
		middle_02_l         = 16,
		middle_03_l         = 17,
		ring_01_l           = 18,
		ring_02_l           = 19,
		ring_03_l           = 20,
		pinky_01_l          = 21,
		pinky_02_l          = 22,
		pinky_03_l          = 23,
		shield_l            = 24,
		lowerarm_twist_01_l = 25,
		upperarm_twist_01_l = 26,
		neck_01             = 27,
		Head                = 28,
		clavicle_r          = 29,
		upperarm_r          = 30,
		lowerarm_r          = 31,
		lowerarm_twist_01_r = 32,
		shield_r            = 33,
		hand_r              = 34,
		pinky_01_r          = 35,
		pinky_02_r          = 36,
		pinky_03_r          = 37,
		ring_01_r           = 38,
		ring_02_r           = 39,
		ring_03_r           = 40,
		middle_01_r         = 41,
		middle_02_r         = 42,
		middle_03_r         = 43,
		index_01_r          = 44,
		index_02_r          = 45,
		index_03_r          = 46,
		thumb_01_r          = 47,
		thumb_02_r          = 48,
		thumb_03_r          = 49,
		upperarm_twist_01_r = 50,
		thigh_l             = 51,
		calf_l              = 52,
		foot_l              = 53,
		ball_l              = 54,
		thigh_r             = 55,
		calf_r              = 56,
		foot_r              = 57,
		ball_r              = 58,
		ik_foot_root        = 59,
		ik_foot_l           = 60,
		ik_foot_r           = 61,
		ik_hand_root        = 62,
		ik_hand_gun         = 63,
		ik_hand_l           = 64,
		weapon_l            = 65,
		ik_hand_r           = 66,
		weapon_r            = 67,
		camera_root         = 68,
		camera_rot_root     = 69,
		Camera              = 70,
		calf_twist_01_l     = 71,
		thigh_twist_01_l    = 72,
		calf_twist_01_r     = 73,
		thigh_twist_01_r    = 74,
		eyelid_l            = 75,
		eyelid_r            = 76
	};

	/**
	 * BoneSkeletalMesh SK_HeavyBoots.SK_HeavyBoots
	 */
	enum class EBone_SK_HeavyBoots : uint8_t
	{
		Root                = 0,
		pelvis              = 1,
		spine_01            = 2,
		spine_02            = 3,
		spine_03            = 4,
		clavicle_l          = 5,
		upperarm_l          = 6,
		lowerarm_l          = 7,
		hand_l              = 8,
		thumb_01_l          = 9,
		thumb_02_l          = 10,
		thumb_03_l          = 11,
		index_01_l          = 12,
		index_02_l          = 13,
		index_03_l          = 14,
		middle_01_l         = 15,
		middle_02_l         = 16,
		middle_03_l         = 17,
		ring_01_l           = 18,
		ring_02_l           = 19,
		ring_03_l           = 20,
		pinky_01_l          = 21,
		pinky_02_l          = 22,
		pinky_03_l          = 23,
		shield_l            = 24,
		lowerarm_twist_01_l = 25,
		upperarm_twist_01_l = 26,
		neck_01             = 27,
		Head                = 28,
		clavicle_r          = 29,
		upperarm_r          = 30,
		lowerarm_r          = 31,
		lowerarm_twist_01_r = 32,
		shield_r            = 33,
		hand_r              = 34,
		pinky_01_r          = 35,
		pinky_02_r          = 36,
		pinky_03_r          = 37,
		ring_01_r           = 38,
		ring_02_r           = 39,
		ring_03_r           = 40,
		middle_01_r         = 41,
		middle_02_r         = 42,
		middle_03_r         = 43,
		index_01_r          = 44,
		index_02_r          = 45,
		index_03_r          = 46,
		thumb_01_r          = 47,
		thumb_02_r          = 48,
		thumb_03_r          = 49,
		upperarm_twist_01_r = 50,
		thigh_l             = 51,
		calf_l              = 52,
		foot_l              = 53,
		ball_l              = 54,
		thigh_r             = 55,
		calf_r              = 56,
		foot_r              = 57,
		ball_r              = 58,
		ik_foot_root        = 59,
		ik_foot_l           = 60,
		ik_foot_r           = 61,
		ik_hand_root        = 62,
		ik_hand_gun         = 63,
		ik_hand_l           = 64,
		weapon_l            = 65,
		ik_hand_r           = 66,
		weapon_r            = 67,
		camera_root         = 68,
		camera_rot_root     = 69,
		Camera              = 70,
		calf_twist_01_l     = 71,
		thigh_twist_01_l    = 72,
		calf_twist_01_r     = 73,
		thigh_twist_01_r    = 74,
		eyelid_l            = 75,
		eyelid_r            = 76
	};

	/**
	 * BoneSkeletalMesh SK_Torch.SK_Torch
	 */
	enum class EBone_SK_Torch : uint8_t
	{
		Root = 0
	};

	/**
	 * BoneSkeletalMesh SK_RoundShield.SK_RoundShield
	 */
	enum class EBone_SK_RoundShield : uint8_t
	{
		Root = 0
	};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
